In [1]:
import pandas as pd
import numpy as np

loan_data = pd.DataFrame({
    "Client": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank"],
    "Age": [25, 42, np.nan, 29, 51, 35],
    "Income": [35000, 72000, 58000, np.nan, 90000, 90000],
    "Loan": [12000, 25000, 18000, 8000, 40000, 40000],
    "Default": [0, 0, 1, 0, 1, 1]
})

loan_data

    Client   Age   Income   Loan  Default
0    Alice  25.0  35000.0  12000        0
1      Bob  42.0  72000.0  25000        0
2  Charlie   NaN  58000.0  18000        1
3    David  29.0      NaN   8000        0
4     Emma  51.0  90000.0  40000        1
5    Frank  35.0  90000.0  40000        1

In [4]:
loan_data.isnull()

   Client    Age  Income   Loan  Default
0   False  False   False  False    False
1   False  False   False  False    False
2   False   True   False  False    False
3   False  False    True  False    False
4   False  False   False  False    False
5   False  False   False  False    False

In [5]:
loan_data.isnull().sum()

Client     0
Age        1
Income     1
Loan       0
Default    0
dtype: int64

In [6]:
loan_data.dropna()

  Client   Age   Income   Loan  Default
0  Alice  25.0  35000.0  12000        0
1    Bob  42.0  72000.0  25000        0
4   Emma  51.0  90000.0  40000        1
5  Frank  35.0  90000.0  40000        1

In [7]:
loan_data["Age"]=loan_data["Age"].fillna(loan_data["Age"].mean())

In [8]:
loan_data

    Client   Age   Income   Loan  Default
0    Alice  25.0  35000.0  12000        0
1      Bob  42.0  72000.0  25000        0
2  Charlie  36.4  58000.0  18000        1
3    David  29.0      NaN   8000        0
4     Emma  51.0  90000.0  40000        1
5    Frank  35.0  90000.0  40000        1

In [9]:
loan_data["Income"]=loan_data["Income"].fillna(loan_data["Income"].mean())

In [10]:
loan_data

    Client   Age   Income   Loan  Default
0    Alice  25.0  35000.0  12000        0
1      Bob  42.0  72000.0  25000        0
2  Charlie  36.4  58000.0  18000        1
3    David  29.0  69000.0   8000        0
4     Emma  51.0  90000.0  40000        1
5    Frank  35.0  90000.0  40000        1

In [11]:
loan_data = pd.concat(
    [loan_data, loan_data.iloc[[0]]],
    ignore_index=True
)

In [12]:
loan_data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [13]:
loan_data

    Client   Age   Income   Loan  Default
0    Alice  25.0  35000.0  12000        0
1      Bob  42.0  72000.0  25000        0
2  Charlie  36.4  58000.0  18000        1
3    David  29.0  69000.0   8000        0
4     Emma  51.0  90000.0  40000        1
5    Frank  35.0  90000.0  40000        1
6    Alice  25.0  35000.0  12000        0

In [14]:
loan_data=loan_data.drop_duplicates()

In [15]:
loan_data

    Client   Age   Income   Loan  Default
0    Alice  25.0  35000.0  12000        0
1      Bob  42.0  72000.0  25000        0
2  Charlie  36.4  58000.0  18000        1
3    David  29.0  69000.0   8000        0
4     Emma  51.0  90000.0  40000        1
5    Frank  35.0  90000.0  40000        1

In [16]:
loan_data.loc[2, "Income"] = 1000000

In [17]:
loan_data.describe()

             Age          Income          Loan   Default
count   6.000000        6.000000      6.000000  6.000000
mean   36.400000   226000.000000  23833.333333  0.500000
std     9.286549   379714.102977  13775.582262  0.547723
min    25.000000    35000.000000   8000.000000  0.000000
25%    30.500000    69750.000000  13500.000000  0.000000
50%    35.700000    81000.000000  21500.000000  0.500000
75%    40.600000    90000.000000  36250.000000  1.000000
max    51.000000  1000000.000000  40000.000000  1.000000

In [18]:
loan_data[loan_data["Income"]>200000]

    Client   Age     Income   Loan  Default
2  Charlie  36.4  1000000.0  18000        1

In [19]:
loan_data.to_csv("clean_loan_data.csv",index=False)

In [20]:
git add .
git commit -m "Day03Data Cleaning"
git push

SyntaxError: invalid syntax (2205533383.py, line 1)